# Generated by Django 4.2.4 on 2023-08-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='auction',
            field=models.BooleanField(default=False, verbose_name='Торг'),
        ),
    ]
