# Generated by Django 4.2.4 on 2023-08-31 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='deleted_at',
        ),
    ]
