# Generated by Django 4.2.4 on 2023-08-31 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_country_delete_mymodel_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='country',
            name='deleted_at',
        ),
    ]
